# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateproperty',
            options={'verbose_name_plural': 'Template properties'},
        ),
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
