# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0002_auto_20160824_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, null=True, unique=True),
        ),
    ]
