# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0003_auto_20160824_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinderQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='templateproperty',
            name='template',
            field=models.ManyToManyField(related_name='template_properties', to='chartwerk.Template'),
        ),
        migrations.AddField(
            model_name='templateproperty',
            name='finder',
            field=models.ManyToManyField(related_name='template_properties', to='chartwerk.FinderQuestion'),
        ),
    ]
