# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:27
from __future__ import unicode_literals

import chartwerk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0004_auto_20160824_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=chartwerk.models.Template.icon_upload_path),
        ),
        migrations.AlterField(
            model_name='templateproperty',
            name='finder',
            field=models.ManyToManyField(blank=True, null=True, related_name='template_properties', to='chartwerk.FinderQuestion'),
        ),
    ]
