# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0005_auto_20160827_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateproperty',
            name='slug',
            field=models.CharField(default='time-series', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
