# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0006_templateproperty_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
