# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0008_auto_20160909_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
