# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0009_auto_20160912_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
