# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0010_auto_20160924_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
