# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 20:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0011_auto_20161012_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='embed_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
