# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartwerk', '0013_auto_20161013_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproperty',
            name='finder',
            field=models.ManyToManyField(blank=True, related_name='template_properties', to='chartwerk.FinderQuestion'),
        ),
    ]
